- name: Run Database Container
  docker_container:
    name: db
    image: mathieumonier/tp-devops-database:latest
    pull: yes
    env_file: /.env
    networks:
      - name: my-network
    volumes:
      - /var/lib/postgresql/data