- name: Run Database Container
  docker_container:
    name: db
    image: mathieumonier/tp-devops-database:latest
    pull: yes
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my-network
    volumes:
      - /var/lib/postgresql/data