- name: Démarrer l'API
  docker_container:
    name: simple-api
    image: "mathieumonier/tp-devops-simple-api:latest"
    pull: yes
    state: started
    env_file: /.env
    networks:
      - name: my-network
      - name: network-front

